# tasks file for virtualbox
---
- name: Debug variables
  debug:
    var: virtualbox_proxy_env
    verbosity: 1
    
- name: add public key
  apt_key:
    id: "{{ item.id }}"
    url: "{{ item.url }}"
    state: present
    validate_certs: "{{ virtualbox_validate_certs }}"
  with_items: "{{ virtualbox_public_keys }}"
  tags:
    - virtualbox-repository-public-key
  environment: "{{ virtualbox_proxy_env }}"
  

- name: add virtualbox repository
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    validate_certs: "{{ virtualbox_validate_certs }}"
  with_items: "{{ virtualbox_repositories }}"
  tags:
    - virtualbox-repository-add
